import { useState } from 'react';
import { BarChart3, Check, Plus, Vote } from 'lucide-react';
import { useAuth } from '../../../app/providers/AuthProvider';
import { useData, useSave } from '../../../shared/hooks/useData';
import { Badge, Button, EmptyState, ErrorState, Field, Loading, Modal, Notice, PageHeading } from '../../../shared/ui';
import type { Survey } from '../../../shared/types/domain';
import { shortDate } from '../../../shared/utils/format';
export function SurveysPage() {
  const query = useData<{ data: Survey[] }>('/surveys'); const { user } = useAuth(); const [creating, setCreating] = useState(false); const canManage = user?.roles.some(r => ['admin', 'ja_director'].includes(r));
  return <div className="page-enter"><PageHeading eyebrow="ESCUCHARNOS" title="Tu voz también construye" description="Descubramos juntos qué le interesa a nuestra comunidad." action={canManage && <Button onClick={() => setCreating(true)}><Plus size={17}/>Nueva encuesta</Button>}/>{query.isPending ? <Loading/> : query.error ? <ErrorState error={query.error}/> : <div className="surveys-grid">{query.data?.data.map(s => <SurveyCard key={`${s.id}-${s.selected_options.join(',')}`} survey={s}/>)}{!query.data?.data.length && <div className="card"><EmptyState title="Una comunidad que escucha" text="Las próximas encuestas aparecerán aquí."/></div>}</div>}{creating && <SurveyForm onClose={() => setCreating(false)}/>}</div>;
}
function SurveyCard({ survey: s }: { survey: Survey }) {
  const [selected, setSelected] = useState(s.selected_options); const save = useSave(`/surveys/${s.id}/response`, 'put');
  return <section className="card survey-card"><div className="split-line"><span className="survey-icon"><Vote size={24}/></span><Badge tone={s.status === 'open' ? 'green' : 'muted'}>{s.status === 'open' ? 'Tu opinión cuenta' : s.status === 'scheduled' ? 'Próximamente' : 'Finalizada'}</Badge></div><h2>{s.title}</h2><p className="muted">{s.description}</p><div className="survey-options">{s.options.map(o => <label className={`survey-option ${selected.includes(o.id) ? 'chosen' : ''}`} key={o.id}><input type="checkbox" checked={selected.includes(o.id)} disabled={s.status !== 'open'} onChange={e => setSelected(e.target.checked ? [...selected, o.id] : selected.filter(id => id !== o.id))}/><span><strong>{o.label}</strong><span className="survey-progress"><i style={{ width: `${o.percentage}%` }}/></span></span><small>{o.percentage}%</small></label>)}</div><p className="small-muted">{s.responses_count} respuestas · Selección múltiple · Cierra el {shortDate(s.closes_at)}</p>{save.error && <Notice error>{save.error.message}</Notice>}{s.selected_options.length > 0 && <p className="saved-vote"><Check size={14}/>Tu respuesta está guardada</p>}{s.status === 'open' && <Button className="full-width" disabled={!selected.length} busy={save.isPending} onClick={() => save.mutate({ option_ids: selected })}>{s.selected_options.length ? 'Actualizar mi respuesta' : 'Compartir mi opinión'}</Button>}<p className="survey-disclaimer">Los porcentajes representan personas que eligieron cada opción.</p></section>;
}
function SurveyForm({ onClose }: { onClose: () => void }) { const save = useSave('/surveys'); return <Modal title="Escuchemos a la comunidad" onClose={onClose}><form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); save.mutate({ title: f.get('title'), description: f.get('description'), closes_at: new Date(String(f.get('closes_at'))).toISOString(), options: String(f.get('options')).split('\n').map(s => s.trim()).filter(Boolean) }, { onSuccess: onClose }); }}>{save.error && <Notice error>{save.error.message}</Notice>}<Field label="Pregunta"><input name="title" required maxLength={180}/></Field><Field label="Descripción"><textarea name="description" rows={2}/></Field><Field label="Opciones" hint="Una por línea. Entre 2 y 12 opciones."><textarea name="options" required rows={5} placeholder={'Caminata en grupo\nTaller de fotografía\nServicio comunitario'}/></Field><Field label="Fecha y hora de cierre"><input name="closes_at" type="datetime-local" required/></Field><div className="modal-actions"><Button type="button" variant="secondary" onClick={onClose}>Cancelar</Button><Button busy={save.isPending}>Publicar encuesta</Button></div></form></Modal>; }
