import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ArrowDown, ArrowRight, ArrowUpRight, CalendarDays, Check, ChevronRight, Clock3, HeartHandshake, House, Leaf, MapPin, Plus, Sparkles, Users } from 'lucide-react';
import { getDashboard } from '../api/dashboard';
import { useAuth } from '../../../app/providers/AuthProvider';
import { Avatar, Badge, EmptyState, ErrorState, Loading } from '../../../shared/ui';
import { fullDate, percent, shortDate, time } from '../../../shared/utils/format';

export function DashboardPage() {
  const { user } = useAuth(); const query = useQuery({ queryKey: ['/dashboard'], queryFn: getDashboard });
  if (query.isPending) return <Loading />;
  if (query.error || !query.data) return <ErrorState error={query.error} retry={() => { void query.refetch(); }} />;
  const d = query.data; const activity = d.next_activity; const gp = user?.roles.some(r => ['admin', 'gp_leader'].includes(r));
  const filled = activity?.opportunities.reduce((sum, o) => sum + o.confirmed_count, 0) || 0;
  const capacity = activity?.opportunities.reduce((sum, o) => sum + o.capacity, 0) || 0;
  const stats = [
    { label: 'Personas en comunidad', value: d.stats.members, icon: Users, note: 'Cada persona cuenta', tone: 'sage' },
    { label: 'Presentes en el último GP', value: d.stats.gp_attendance, icon: House, note: 'Encuentros que nos acercan', tone: 'sand' },
    { label: 'Conexión GP → JA', value: percent(d.stats.connection_rate), icon: HeartHandshake, note: 'Del encuentro a la participación', tone: 'lavender' },
    { label: 'Responsabilidades cumplidas', value: d.stats.active_roles, icon: Sparkles, note: 'Talentos puestos en acción', tone: 'rose' },
  ];
  return <div className="dashboard page-enter">
    <div className="page-heading dashboard-heading"><div><p className="eyebrow"><span className="status-dot" /> {d.scope_name.toUpperCase()}</p><h1>Hola, {user?.person.full_name.split(' ')[0]} <span className="greeting-sun">✳</span></h1><p className="page-description">Cada encuentro es una oportunidad para crecer juntos.</p></div><div className="heading-actions"><span className="date-pill"><CalendarDays size={16} />{fullDate(new Date().toISOString())}</span>{gp && <Link to="/reuniones" className="button button-primary"><Plus size={17} />Registrar reunión</Link>}</div></div>
    <section className="welcome-banner"><div><span className="banner-kicker"><Leaf size={15} /> PERTENECER. PARTICIPAR. SERVIR.</span><h2>Una comunidad.<br /><span>Muchas formas de aportar.</span></h2><p>Conecta los talentos de tu grupo con su próximo propósito.</p><Link to="/oportunidades" className="banner-link">Descubrir oportunidades <ArrowRight size={17} /></Link></div><div className="connection-art" aria-hidden="true"><div className="art-orbit outer"/><div className="art-orbit inner"/><div className="art-center"><Leaf size={38} strokeWidth={1.3}/></div><div className="art-node node-one"><House size={24}/><span>Pertenecer</span></div><div className="art-node node-two"><HeartHandshake size={24}/><span>Servir</span></div><div className="art-node node-three"><Sparkles size={24}/><span>Participar</span></div><span className="art-star">✳</span><span className="art-dot"/></div></section>
    <section className="stats-grid" aria-label="Indicadores de comunidad">{stats.map(({ label, value, icon: Icon, note, tone }) => <article className="stat-card" key={label}><div className="stat-top"><span>{label}</span><span className={`stat-icon ${tone}`}><Icon size={18}/></span></div><strong className="stat-number">{value}</strong><p><span className="stat-tick"><Check size={12}/></span>{note}</p></article>)}</section>
    <div className="dashboard-main-grid"><section className="card participation-chart"><div className="section-heading"><div><p className="eyebrow">EL IMPACTO DE ENCONTRARNOS</p><h2>Así crece nuestra conexión</h2></div><span className="subtle-chip">Últimos 6 ciclos</span></div><div className="chart-legend"><span><i className="legend-dot green"/>Asistencia GP</span><span><i className="legend-dot gold"/>Asistencia JA</span></div><div className="chart-container"><ResponsiveContainer width="100%" height="100%"><AreaChart data={d.trend} margin={{ top: 12, right: 12, left: -28, bottom: 0 }}><defs><linearGradient id="gpFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#507a60" stopOpacity={0.16}/><stop offset="100%" stopColor="#507a60" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 6" vertical={false} stroke="#e8ece7"/><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fill: '#8a928c', fontSize: 11 }} dy={12}/><YAxis allowDecimals={false} axisLine={false} tickLine={false} tick={{ fill: '#8a928c', fontSize: 11 }}/><Tooltip contentStyle={{ borderRadius: 12, border: '1px solid #e6e9e3', fontSize: 12 }} /><Area name="Asistentes GP" type="monotone" dataKey="gp" stroke="#507a60" strokeWidth={2.5} fill="url(#gpFill)" dot={{ r: 3, fill: '#507a60', stroke: '#fff', strokeWidth: 2 }}/><Area name="Asistentes JA" type="monotone" dataKey="ja" stroke="#d5ae68" strokeWidth={2.5} strokeDasharray="5 4" fill="transparent" dot={false}/></AreaChart></ResponsiveContainer></div><div className="chart-footnote"><span><HeartHandshake size={15}/>Medimos conexiones, celebramos a las personas.</span><Link to="/indicadores">Ver detalle <ArrowUpRight size={15}/></Link></div></section>
    <section className="card next-activity"><div className="section-heading"><h2>Nuestro próximo encuentro</h2><CalendarDays size={18}/></div>{activity ? <><div className="activity-art"><span className="activity-art-label">MINISTERIO JOVEN</span><span className="activity-art-title">Juntos,<br/><em>hacemos más.</em></span><div className="abstract-leaf leaf-one"/><div className="abstract-leaf leaf-two"/><div className="abstract-leaf leaf-three"/><span className="activity-date"><strong>{new Date(activity.starts_at).getDate()}</strong>{new Intl.DateTimeFormat('es', { month: 'short' }).format(new Date(activity.starts_at)).toUpperCase()}</span></div><div className="activity-card-info"><Badge>{activity.activity_type.name}</Badge><h3>{activity.title}</h3><p><Clock3 size={14}/>{shortDate(activity.starts_at)} · {time(activity.starts_at)}</p><p><MapPin size={14}/>{activity.place || 'Lugar por confirmar'}</p><div className="host-group"><span className="host-icon"><House size={17}/></span><div><small>GP RESPONSABLE</small><strong>{activity.group?.name || 'Por asignar'}</strong></div><Check size={15}/></div><div className="capacity-label"><span>Un lugar para cada talento</span><strong>{filled}/{capacity} cupos</strong></div><div className="progress"><span style={{ width: `${capacity ? Math.min(100, filled / capacity * 100) : 0}%` }}/></div><Link to={`/actividades/${activity.id}`} className="button button-secondary full-width">Ver actividad <ArrowRight size={16}/></Link></div></> : <EmptyState title="Lo mejor está por venir" text="Las próximas actividades aparecerán aquí cuando se publiquen."/>}</section></div>
    <div className="dashboard-bottom-grid"><section className="card"><div className="section-heading"><div><p className="eyebrow">DONDE TODO COMIENZA</p><h2>Nuestros grupos pequeños</h2></div><Link className="text-link" to="/grupos">Ver grupos <ArrowRight size={15}/></Link></div><div className="group-preview-list">{d.groups.slice(0, 3).map((group, index) => <Link to={`/grupos?group=${group.id}`} className="group-preview" key={group.id}><span className={`group-mini-icon ${['sage', 'sand', 'lavender'][index % 3]}`}><House size={21}/></span><div><strong>{group.name}</strong><small>{group.leader?.full_name || 'Líder por asignar'}</small></div><span className="member-count"><Users size={13}/>{group.members_count}</span><ChevronRight size={16}/></Link>)}{!d.groups.length && <p className="muted">Tu grupo aparecerá aquí cuando sea asignado.</p>}</div></section><section className="card"><div className="section-heading"><div><p className="eyebrow">ESTAR CERCA IMPORTA</p><h2>Un momento para acompañar</h2></div><span className="soft-circle"><HeartHandshake size={20}/></span></div>{d.alerts.length ? <><p className="section-copy">Un saludo puede hacer la diferencia. Estas personas llevan un tiempo sin acompañarnos.</p><div className="follow-preview">{d.alerts.slice(0, 2).map((alert, index) => <div key={alert.id}><Avatar name={alert.person.full_name} index={index + 2}/><span><strong>{alert.person.full_name}</strong><small>{alert.consecutive_count} reuniones sin asistir</small></span><Link to="/seguimiento" className="round-link" aria-label={`Acompañar a ${alert.person.full_name}`}><ArrowUpRight size={18}/></Link></div>)}</div></> : <div className="all-connected"><span><Check size={22}/></span><div><strong>Estamos al día</strong><p>No hay seguimientos pendientes en tu comunidad.</p></div></div>}<Link to="/seguimiento" className="text-link">Ir a acompañamiento <ArrowRight size={15}/></Link></section></div>
    <div className="dashboard-bottom-message"><Leaf size={15}/><span>Detrás de cada número, hay una persona. Detrás de cada encuentro, una historia.</span></div>
  </div>;
}
