import { useState, type FormEvent } from 'react';
import { Navigate } from 'react-router-dom';
import { ArrowRight, Eye, EyeOff, Leaf, HeartHandshake, Sparkles } from 'lucide-react';
import { useAuth } from '../../../app/providers/AuthProvider';
import { Button, Field, Notice } from '../../../shared/ui';

export function LoginPage() {
  const { user, login } = useAuth(); const [visible, setVisible] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  if (user) return <Navigate to="/" replace />;
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); const values = new FormData(event.currentTarget); try { await login(String(values.get('username')), String(values.get('password'))); } catch (error) { setError(error instanceof Error ? error.message : 'No se pudo conectar con el servidor.'); } finally { setBusy(false); } }
  return <div className="login-page"><section className="login-story"><div className="brand"><span className="brand-symbol"><Leaf size={25} /></span><span>conecta.</span></div><div className="login-story-content"><span className="overline"><span className="status-dot" /> COMUNIDAD EN ACCIÓN</span><h1>Un lugar para ti.<br />Un propósito<br /><em>para compartir.</em></h1><p>Conectamos encuentros, talentos y oportunidades para crecer y servir juntos.</p><div className="login-values"><span><HeartHandshake size={20} /> Pertenecer</span><span><Sparkles size={20} /> Participar</span><span><Leaf size={20} /> Servir</span></div></div><p className="login-bottom">GRUPOS PEQUEÑOS + MINISTERIO JOVEN</p><div className="login-orbit orbit-one" /><div className="login-orbit orbit-two" /></section><section className="login-form-side"><div className="login-form-wrap"><p className="eyebrow">QUÉ BUENO TENERTE AQUÍ</p><h2>Bienvenido de nuevo</h2><p className="muted">Tu comunidad y tu próxima oportunidad te esperan.</p><form onSubmit={submit}>{error && <Notice error>{error}</Notice>}<Field label="Usuario"><input name="username" autoComplete="username" required placeholder="Tu nombre de usuario" autoFocus /></Field><Field label="Contraseña"><span className="password-input"><input name="password" type={visible ? 'text' : 'password'} autoComplete="current-password" required placeholder="Ingresa tu contraseña" /><button type="button" className="icon-button" aria-label={visible ? 'Ocultar contraseña' : 'Mostrar contraseña'} onClick={() => setVisible(!visible)}>{visible ? <EyeOff size={18} /> : <Eye size={18} />}</button></span></Field><Button type="submit" busy={busy} className="full-width">Entrar a mi comunidad <ArrowRight size={18} /></Button></form><p className="login-help">¿Necesitas acceso o recuperar tu contraseña?<br /><strong>Comunícate con el administrador de tu iglesia.</strong></p></div><span className="login-copyright">Conecta · Cada persona tiene algo para aportar.</span></section></div>;
}
