import { useState } from 'react';
import { Check, HeartHandshake, Sparkles, X } from 'lucide-react';
import { useAuth } from '../../../app/providers/AuthProvider';
import { useData, useSave } from '../../../shared/hooks/useData';
import { Avatar, Badge, Button, Field, Modal, Notice } from '../../../shared/ui';
import type { Activity, Opportunity, Paged, Person } from '../../../shared/types/domain';

export function CommitmentForm({ activity, opportunity: o, onClose }: { activity: Activity; opportunity: Opportunity; onClose: () => void }) {
  const { user } = useAuth(); const people = useData<Paged<Person>>('/people?per_page=100'); const suggestions = useData<{ data: { person: Person; reasons: string[] }[] }>(`/opportunities/${o.id}/recommendations`); const [personId, setPersonId] = useState(user?.person.id || 0); const [consent, setConsent] = useState(false); const save = useSave(`/opportunities/${o.id}/commitments`); const full = o.confirmed_count >= o.capacity; const canAccept = user?.roles.some(r => ['admin', 'gp_leader'].includes(r)); const available = activity.status === 'published' && new Date(activity.ends_at) > new Date();
  return <Modal title={o.title} description={`${activity.title} · ${o.confirmed_count} de ${o.capacity} cupos cubiertos`} onClose={onClose}><p className="modal-intro">{o.description}</p>{o.commitments.length > 0 && <div className="commitment-team"><p className="eyebrow">EL EQUIPO HASTA AHORA</p>{o.commitments.map((c, i) => <div className="team-row" key={c.id}><Avatar name={c.person.full_name} index={i}/><strong>{c.person.full_name}</strong>{available && (user?.person.id === c.person.id || user?.roles.includes('admin') || (user?.roles.includes('gp_leader') && c.person.group?.id === user.group_id)) ? <CancelCommitment id={c.id} onDone={onClose}/> : <Badge><Check size={12}/>Confirmado</Badge>}</div>)}</div>}{!full && available && <form onSubmit={e => { e.preventDefault(); save.mutate({ person_id: personId, acceptance_confirmed: consent }, { onSuccess: onClose }); }}>{save.error && <Notice error>{save.error.message}</Notice>}{canAccept ? <Field label="¿Quién desea participar?"><select value={personId} onChange={e => { setPersonId(Number(e.target.value)); setConsent(false); }}>{people.data?.data.filter(p => p.status === 'active').map(p => <option key={p.id} value={p.id}>{p.full_name}</option>)}</select></Field> : <div className="your-commitment"><Avatar name={user?.person.full_name || ''}/><strong>{user?.person.full_name}</strong></div>}{suggestions.data?.data.find(s => s.person.id === personId) && <div className="recommendation-note"><Sparkles size={17}/><span>{suggestions.data.data.find(s => s.person.id === personId)?.reasons.join('. ')}.</span></div>}<label className="check-field consent-field"><input type="checkbox" checked={consent} onChange={e => setConsent(e.target.checked)} required/><span>{personId === user?.person.id ? 'Quiero participar y confirmo mi disponibilidad para este horario.' : 'Esta persona aceptó participar y confirmó su disponibilidad.'}</span></label><div className="modal-actions"><Button type="button" variant="secondary" onClick={onClose}>Volver</Button><Button type="submit" busy={save.isPending} disabled={!consent}><HeartHandshake size={17}/>Confirmar compromiso</Button></div></form>}{full && <Notice>Este equipo está completo. Hay otras oportunidades para compartir tus talentos.</Notice>}</Modal>;
}
function CancelCommitment({ id, onDone }: { id: number; onDone: () => void }) { const save = useSave(`/commitments/${id}/cancel`); const [confirm, setConfirm] = useState(false); return <div>{save.error && <small role="alert">{save.error.message}</small>}<Button variant="ghost" busy={save.isPending} onClick={() => confirm ? save.mutate({}, { onSuccess: onDone }) : setConfirm(true)}><X size={14}/>{confirm ? 'Confirmar cancelación' : 'Liberar cupo'}</Button></div>; }
