export type Role = 'admin' | 'gp_leader' | 'ja_director' | 'member';
export interface Session { id: number; username: string; person: Person; roles: Role[]; group_id: number | null; must_change_password: boolean }
export interface CatalogItem { id: number; name: string; is_active?: boolean }
export interface Person { id: number; full_name: string; phone: string | null; email: string | null; status: string; talents: CatalogItem[]; interests: CatalogItem[]; group: { id: number; name: string } | null; learning?: CatalogItem[]; availability?: CatalogItem[] }
export interface Group { id: number; name: string; description: string | null; meeting_place: string | null; usual_weekday: number; usual_time: string; status: string; members_count: number; leader: { full_name: string } | null; color: string }
export interface Opportunity { id: number; title: string; description: string | null; capacity: number; confirmed_count: number; talent: CatalogItem | null; closed_at: string | null; commitments: { id: number; person: Person; status: string }[] }
export interface Activity { id: number; title: string; description: string | null; place: string | null; starts_at: string; ends_at: string; status: string; is_primary: boolean; activity_type: CatalogItem; group: Group | null; opportunities: Opportunity[]; result: { summary: string; beneficiary_count: number | null; final_note: string | null } | null; attendees?: { person_id: number; status: string }[]; participations?: { person_id: number; opportunity_id: number }[] }
export interface Meeting { id: number; group_id: number; starts_at: string; status: string; next_activity_note: string | null; group: Group; attendances: { person_id: number; status: string; person: Person }[] }
export interface Alert { id: number; consecutive_count: number; status: string; person: Person; group_name: string; last_contact_at: string | null }
export interface Dashboard { scope_name: string; stats: { members: number; gp_attendance: number; connection_rate: number | null; active_roles: number }; trend: { label: string; gp: number; ja: number }[]; next_activity: Activity | null; groups: Group[]; alerts: Alert[]; recent: { id: number; title: string; description: string; occurred_at: string; kind: string }[]; attendance_comparison: { gp: number; ja: number; both: number; active: number } }
export interface Survey { id: number; title: string; description: string | null; status: string; closes_at: string; responses_count: number; options: { id: number; label: string; count: number; percentage: number }[]; selected_options: number[] }
export interface ServiceNeed { id: number; description: string; status: string; reported_at: string; responsible: Person; activity_id: number | null }
export interface Catalogs { talents: CatalogItem[]; interests: CatalogItem[]; activity_types: CatalogItem[]; responsibilities: CatalogItem[]; availability_slots: CatalogItem[] }
export interface Paged<T> { data: T[]; current_page: number; last_page: number; total: number }
