import { useState } from 'react';
import { Check, HeartHandshake, MessageCircle, Phone } from 'lucide-react';
import { api } from '../../../shared/api/client';
import { useData } from '../../../shared/hooks/useData';
import { useQueryClient } from '@tanstack/react-query';
import { Avatar, Badge, Button, EmptyState, ErrorState, Notice, PageHeading } from '../../../shared/ui';
import type { Alert } from '../../../shared/types/domain';
import { shortDate } from '../../../shared/utils/format';
export function FollowUpsPage() {
  const query = useData<{ data: Alert[] }>('/absence-alerts'); const client = useQueryClient(); const [busy, setBusy] = useState<number | null>(null); const [error, setError] = useState('');
  async function contact(alert: Alert, action: string) { setBusy(alert.id); setError(''); const popup = action === 'message_opened' ? window.open('about:blank', '_blank') : null; if (popup) popup.opener = null; try { const result = await api.post<{ contact_url: string | null }>(`/absence-alerts/${alert.id}/follow-ups`, { action }); if (result.contact_url && popup) popup.location.href = result.contact_url; await client.invalidateQueries(); } catch (e) { popup?.close(); setError(e instanceof Error ? e.message : 'No pudimos registrar el contacto.'); } finally { setBusy(null); } }
  return <div className="page-enter"><PageHeading eyebrow="ACOMPAÑAR" title="Un saludo puede cambiar el día" description="Estar cerca empieza por un pequeño gesto de interés."/><div className="section-intro warm"><span className="intro-icon"><HeartHandshake size={28}/></span><div><h3>Acompañamos personas, cuidamos vínculos</h3><p>Estos recordatorios te ayudan a mantener el contacto, sin guardar conversaciones personales.</p></div></div>{error && <Notice error>{error}</Notice>}{query.error && <ErrorState error={query.error}/>}<div className="followups-grid">{query.data?.data.map((a, i) => <article className="card followup-card" key={a.id}><div className="split-line"><Avatar name={a.person.full_name} size="lg" index={i}/><Badge tone={a.status === 'contacted' ? 'green' : 'amber'}>{a.status === 'contacted' ? 'Contacto registrado' : 'Por acompañar'}</Badge></div><h2>{a.person.full_name}</h2><p className="muted">GP {a.group_name}</p><div className="followup-context"><HeartHandshake size={18}/><p>Lleva <strong>{a.consecutive_count} reuniones</strong> sin asistir.<br/>Un mensaje puede acercarnos de nuevo.</p></div>{a.last_contact_at && <p className="small-muted">Último contacto: {shortDate(a.last_contact_at)}</p>}<div className="followup-actions"><Button variant="secondary" busy={busy === a.id} onClick={() => { void contact(a, 'contacted'); }}><Check size={16}/>Ya conversé</Button><Button disabled={!a.person.phone || busy !== null} onClick={() => { void contact(a, 'message_opened'); }}><MessageCircle size={16}/>Enviar mensaje</Button></div>{!a.person.phone && <small className="muted">Agrega un teléfono a su perfil para abrir la mensajería.</small>}</article>)}</div>{query.data?.data.length === 0 && <div className="card"><EmptyState title="Los vínculos están al día" text="No hay alertas de acompañamiento pendientes. Qué bueno seguir encontrándonos."/></div>}</div>;
}
