import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, HeartHandshake, Plus, Sprout } from 'lucide-react';
import { useAuth } from '../../../app/providers/AuthProvider';
import { useData, useSave } from '../../../shared/hooks/useData';
import { Avatar, Badge, Button, EmptyState, ErrorState, Field, Modal, Notice, PageHeading } from '../../../shared/ui';
import type { ServiceNeed } from '../../../shared/types/domain';
import { shortDate } from '../../../shared/utils/format';
export function ServicePage() {
  const query = useData<{ data: ServiceNeed[] }>('/service-needs'); const { user } = useAuth(); const [creating, setCreating] = useState(false); const [convert, setConvert] = useState<ServiceNeed | null>(null); const canManage = user?.roles.some(r => ['admin', 'ja_director'].includes(r));
  return <div className="page-enter"><PageHeading eyebrow="SERVIR" title="Pequeñas acciones. Impacto real." description="Escuchamos las necesidades de nuestra comunidad y las convertimos en oportunidades de servicio." action={<Button onClick={() => setCreating(true)}><Plus size={17}/>Registrar necesidad</Button>}/><div className="section-intro warm"><span className="intro-icon"><Sprout size={29}/></span><div><h3>El servicio comienza por mirar a nuestro alrededor</h3><p>Una necesidad, un equipo y la disposición de aportar pueden hacer la diferencia.</p></div></div>{query.error && <ErrorState error={query.error}/>}<div className="service-grid">{query.data?.data.map((n, i) => <article className="card service-card" key={n.id}><div className="split-line"><span className={`service-icon ${i % 2 ? 'sand' : 'sage'}`}><HeartHandshake size={25}/></span><Badge tone={n.activity_id ? 'green' : 'amber'}>{n.activity_id ? 'En planificación' : 'Una oportunidad de ayudar'}</Badge></div><h2>{n.description}</h2><div className="service-responsible"><Avatar name={n.responsible.full_name} size="sm" index={i}/><span><small>RESPONSABLE</small><strong>{n.responsible.full_name}</strong></span><small>{shortDate(n.reported_at)}</small></div>{n.activity_id ? <Link to={`/actividades/${n.activity_id}`} className="button button-secondary full-width">Ver actividad <ArrowRight size={16}/></Link> : canManage && <Button variant="secondary" className="full-width" onClick={() => setConvert(n)}>Convertir en actividad <ArrowRight size={16}/></Button>}</article>)}</div>{query.data?.data.length === 0 && <div className="card"><EmptyState title="Una mirada atenta es el primer paso" text="Registra una necesidad de servicio para comenzar."/></div>}{creating && <NeedForm personId={user!.person.id} onClose={() => setCreating(false)}/>} {convert && <ConvertForm need={convert} onClose={() => setConvert(null)}/>}</div>;
}
function NeedForm({ personId, onClose }: { personId: number; onClose: () => void }) { const save = useSave('/service-needs'); return <Modal title="¿Cómo podemos ayudar?" description="Describe la necesidad sin incluir información personal sensible. Tú serás el contacto inicial." onClose={onClose}><form onSubmit={e => { e.preventDefault(); save.mutate({ description: new FormData(e.currentTarget).get('description'), responsible_person_id: personId }, { onSuccess: onClose }); }}>{save.error && <Notice error>{save.error.message}</Notice>}<Field label="Necesidad de servicio"><textarea name="description" required rows={5} maxLength={2000}/></Field><div className="modal-actions"><Button busy={save.isPending}>Registrar necesidad</Button></div></form></Modal>; }
function ConvertForm({ need, onClose }: { need: ServiceNeed; onClose: () => void }) { const save = useSave(`/service-needs/${need.id}/convert`); return <Modal title="De la intención a la acción" description="Se creará una actividad en borrador para completar sus oportunidades." onClose={onClose}><form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); save.mutate({ title: f.get('title'), place: f.get('place'), starts_at: new Date(String(f.get('starts_at'))).toISOString(), ends_at: new Date(String(f.get('ends_at'))).toISOString() }, { onSuccess: onClose }); }}>{save.error && <Notice error>{save.error.message}</Notice>}<Field label="Nombre de la actividad"><input name="title" required maxLength={180}/></Field><div className="form-grid"><Field label="Inicio"><input name="starts_at" type="datetime-local" required/></Field><Field label="Fin"><input name="ends_at" type="datetime-local" required/></Field></div><Field label="Lugar"><input name="place"/></Field><div className="modal-actions"><Button busy={save.isPending}>Crear actividad</Button></div></form></Modal>; }
